# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{translation_panel}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mik-die"]
  s.date = %q{2011-08-09}
  s.description = %q{I18n backend, based on redis, with frontend panel for translations}
  s.email = %q{MikDiet@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/translation_panel.js.coffee",
    "app/assets/stylesheets/translation_panel.css.scss",
    "app/controllers/translations/translations_controller.rb",
    "config/routes.rb",
    "lib/generators/translation_panel/install_generator.rb",
    "lib/translation_panel.rb",
    "lib/translation_panel/engine.rb",
    "lib/translation_panel/filter.rb",
    "lib/translation_panel/redis_backend.rb",
    "spec/app/.gitignore",
    "spec/app/app/controllers/application_controller.rb",
    "spec/app/app/controllers/home_controller.rb",
    "spec/app/app/views/home/index.html.erb",
    "spec/app/app/views/home/without_head.html.erb",
    "spec/app/config.ru",
    "spec/app/config/application.rb",
    "spec/app/config/boot.rb",
    "spec/app/config/environment.rb",
    "spec/app/config/environments/development.rb",
    "spec/app/config/environments/production.rb",
    "spec/app/config/environments/test.rb",
    "spec/app/config/initializers/i18n.rb",
    "spec/app/config/initializers/secret_token.rb",
    "spec/app/config/initializers/session_store.rb",
    "spec/app/config/redis.yml",
    "spec/app/config/redis/test.conf",
    "spec/app/config/routes.rb",
    "spec/app/db/.gitkeep",
    "spec/integration/navigation_spec.rb",
    "spec/lib/redis_backend_spec.rb",
    "spec/spec_helper.rb",
    "spec/translation_panel_spec.rb",
    "translation_panel.gemspec"
  ]
  s.homepage = %q{http://github.com/Mik-die/translation_panel}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{I18n backend}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_development_dependency(%q<redis>, [">= 0"])
      s.add_development_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0.4.0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.0.0.beta"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0.4.0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.0.0.beta"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0.4.0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.0.0.beta"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

